[pytest]
addopts = --import-mode=importlib
python_classes = Test* !TestRun* !TestCase* !TestResult*
filterwarnings =
    ignore::DeprecationWarning
    ignore::pydantic.warnings.PydanticDeprecatedSince20
    ignore::sqlalchemy.exc.MovedIn20Warning
